// Copyright 2024-2026 Andrey Vasilevsky <anvanster@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! Ask-backs — store + types (v0.8.5).
//!
//! An ask-back is one clarifying question, generated by Haiku at
//! capture time, queued for the *next* session in the same project.
//! The mechanism is the proactive counterpart to [[asks]]:
//!
//! - [[mistakes]] (v0.8.2): agent realizes mid-task it was corrected,
//!   logs the correction explicitly.
//! - [[asks]] (v0.8.4): agent realizes after the fact it should have
//!   asked a question up front, logs it explicitly.
//! - **ask_backs** (v0.8.5): *capture itself* notices a failure/partial
//!   outcome paired with vague intent, drafts the question on the
//!   agent's behalf, and surfaces it at the start of the next session
//!   in that project.
//!
//! The agent doesn't need to remember anything; the system reaches for
//! the gap.
//!
//! Storage:
//! - One row per drafted question, keyed by autoincrement id.
//! - Status: `pending` (drafted, not yet shown) → `served` (returned
//!   to the agent via `tempera_session_start`) → optional `dismissed`
//!   for manual cleanup.
//! - Partial unique index enforces **at-most-one-pending-per-project**.
//!   The capture hook calls `record` unconditionally and treats a
//!   unique-violation as the natural debounce signal.
//!
//! This module is the lean store + types — shared by both binaries.
//! The Haiku-backed generator lives in `ask_back_gen.rs` (main only).

#![allow(dead_code)]

use anyhow::{Context, Result};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use sqlx::Row;
use sqlx::sqlite::{SqliteConnectOptions, SqlitePool};
use std::path::Path;

use crate::config::Config;

static MIGRATOR: sqlx::migrate::Migrator = sqlx::migrate!("./migrations");

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum AskBackStatus {
    Pending,
    Served,
    Dismissed,
}

impl AskBackStatus {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Pending => "pending",
            Self::Served => "served",
            Self::Dismissed => "dismissed",
        }
    }

    pub fn from_str(s: &str) -> Option<Self> {
        Some(match s {
            "pending" => Self::Pending,
            "served" => Self::Served,
            "dismissed" => Self::Dismissed,
            _ => return None,
        })
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AskBack {
    pub id: Option<i64>,
    pub project: String,
    pub episode_id: String,
    pub question: String,
    pub status: AskBackStatus,
    pub model: String,
    pub created_at: DateTime<Utc>,
    pub served_at: Option<DateTime<Utc>>,
}

#[derive(Clone)]
pub struct AskBackStore {
    pool: SqlitePool,
}

/// Outcome of attempting to insert a new pending ask-back.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RecordOutcome {
    /// New row written; carries the assigned id.
    Inserted(i64),
    /// A pending row already exists for this project; nothing written.
    /// The capture hook treats this as the natural debounce signal.
    AlreadyPending,
}

impl AskBackStore {
    pub async fn open_default() -> Result<Self> {
        let path = Config::data_dir()?.join("jobs.sqlite");
        Self::open(&path).await
    }

    pub async fn open(path: &Path) -> Result<Self> {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let opts = SqliteConnectOptions::new()
            .filename(path)
            .create_if_missing(true);
        let pool = SqlitePool::connect_with(opts)
            .await
            .with_context(|| format!("Failed to open ask_backs DB at {}", path.display()))?;
        MIGRATOR
            .run(&pool)
            .await
            .context("Failed to run ask_back migrations")?;
        Ok(Self { pool })
    }

    pub async fn open_in_memory() -> Result<Self> {
        let pool = SqlitePool::connect("sqlite::memory:").await?;
        MIGRATOR.run(&pool).await?;
        Ok(Self { pool })
    }

    /// Insert a pending ask-back. Returns `AlreadyPending` if the
    /// project already has a pending row (caught via the partial
    /// unique index — that's the design, not a bug).
    pub async fn record(&self, ab: &AskBack) -> Result<RecordOutcome> {
        let result = sqlx::query(
            "INSERT INTO ask_backs
                (project, episode_id, question, status, model, created_at, served_at)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)",
        )
        .bind(&ab.project)
        .bind(&ab.episode_id)
        .bind(&ab.question)
        .bind(ab.status.as_str())
        .bind(&ab.model)
        .bind(ab.created_at.timestamp())
        .bind(ab.served_at.map(|d| d.timestamp()))
        .execute(&self.pool)
        .await;
        match result {
            Ok(r) => Ok(RecordOutcome::Inserted(r.last_insert_rowid())),
            Err(e) => {
                if Self::is_unique_violation(&e) {
                    Ok(RecordOutcome::AlreadyPending)
                } else {
                    Err(e.into())
                }
            }
        }
    }

    fn is_unique_violation(e: &sqlx::Error) -> bool {
        if let sqlx::Error::Database(db_err) = e {
            // SQLite reports UNIQUE violations with code 2067 or 1555.
            if let Some(code) = db_err.code() {
                return code == "2067" || code == "1555";
            }
            // Fallback: message check, since sqlx-sqlite has varied across
            // versions on whether `.code()` is populated.
            return db_err.message().to_uppercase().contains("UNIQUE");
        }
        false
    }

    /// Returns true when a pending ask-back already exists for this
    /// project. Cheaper than calling `record` and discarding the
    /// outcome when callers want to gate other work too.
    pub async fn has_pending_for_project(&self, project: &str) -> Result<bool> {
        let row = sqlx::query(
            "SELECT 1 FROM ask_backs WHERE project = ?1 AND status = 'pending' LIMIT 1",
        )
        .bind(project)
        .fetch_optional(&self.pool)
        .await?;
        Ok(row.is_some())
    }

    /// Fetch the pending ask-back for a project, if any.
    pub async fn get_pending_for_project(&self, project: &str) -> Result<Option<AskBack>> {
        let row = sqlx::query(
            "SELECT id, project, episode_id, question, status, model, created_at, served_at
             FROM ask_backs WHERE project = ?1 AND status = 'pending'
             ORDER BY created_at DESC LIMIT 1",
        )
        .bind(project)
        .fetch_optional(&self.pool)
        .await?;
        row.as_ref().map(Self::row_to_ask_back).transpose()
    }

    /// Mark an ask-back as served and stamp `served_at = now`. Idempotent.
    pub async fn mark_served(&self, id: i64) -> Result<()> {
        sqlx::query("UPDATE ask_backs SET status = 'served', served_at = ?2 WHERE id = ?1")
            .bind(id)
            .bind(Utc::now().timestamp())
            .execute(&self.pool)
            .await?;
        Ok(())
    }

    pub async fn mark_dismissed(&self, id: i64) -> Result<()> {
        sqlx::query("UPDATE ask_backs SET status = 'dismissed' WHERE id = ?1")
            .bind(id)
            .execute(&self.pool)
            .await?;
        Ok(())
    }

    pub async fn list_all(&self, limit: i64) -> Result<Vec<AskBack>> {
        let rows = sqlx::query(
            "SELECT id, project, episode_id, question, status, model, created_at, served_at
             FROM ask_backs ORDER BY created_at DESC LIMIT ?1",
        )
        .bind(limit)
        .fetch_all(&self.pool)
        .await?;
        rows.iter().map(Self::row_to_ask_back).collect()
    }

    pub async fn list_by_project(&self, project: &str, limit: i64) -> Result<Vec<AskBack>> {
        let rows = sqlx::query(
            "SELECT id, project, episode_id, question, status, model, created_at, served_at
             FROM ask_backs WHERE project = ?1
             ORDER BY created_at DESC LIMIT ?2",
        )
        .bind(project)
        .bind(limit)
        .fetch_all(&self.pool)
        .await?;
        rows.iter().map(Self::row_to_ask_back).collect()
    }

    fn row_to_ask_back(row: &sqlx::sqlite::SqliteRow) -> Result<AskBack> {
        let status_s: String = row.get("status");
        let created_ts: i64 = row.get("created_at");
        let served_ts: Option<i64> = row.get("served_at");
        Ok(AskBack {
            id: Some(row.get::<i64, _>("id")),
            project: row.get("project"),
            episode_id: row.get("episode_id"),
            question: row.get("question"),
            status: AskBackStatus::from_str(&status_s).unwrap_or(AskBackStatus::Pending),
            model: row.get("model"),
            created_at: DateTime::<Utc>::from_timestamp(created_ts, 0).unwrap_or_default(),
            served_at: served_ts.and_then(|t| DateTime::<Utc>::from_timestamp(t, 0)),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn mk(project: &str, episode: &str, question: &str) -> AskBack {
        AskBack {
            id: None,
            project: project.to_string(),
            episode_id: episode.to_string(),
            question: question.to_string(),
            status: AskBackStatus::Pending,
            model: "haiku".to_string(),
            created_at: Utc::now(),
            served_at: None,
        }
    }

    #[test]
    fn status_roundtrip_via_str() {
        for s in [
            AskBackStatus::Pending,
            AskBackStatus::Served,
            AskBackStatus::Dismissed,
        ] {
            assert_eq!(AskBackStatus::from_str(s.as_str()), Some(s));
        }
        assert_eq!(AskBackStatus::from_str("bogus"), None);
    }

    #[tokio::test]
    async fn record_inserts_when_no_pending() {
        let s = AskBackStore::open_in_memory().await.unwrap();
        let outcome = s.record(&mk("p", "ep-1", "Why X?")).await.unwrap();
        assert!(matches!(outcome, RecordOutcome::Inserted(_)));
        assert!(s.has_pending_for_project("p").await.unwrap());
    }

    #[tokio::test]
    async fn record_returns_already_pending_on_duplicate() {
        let s = AskBackStore::open_in_memory().await.unwrap();
        let _ = s.record(&mk("p", "ep-1", "Q1")).await.unwrap();
        let outcome = s.record(&mk("p", "ep-2", "Q2")).await.unwrap();
        assert_eq!(outcome, RecordOutcome::AlreadyPending);
        let rows = s.list_by_project("p", 10).await.unwrap();
        // Second insert was suppressed; only the first row remains.
        assert_eq!(rows.len(), 1);
        assert_eq!(rows[0].question, "Q1");
    }

    #[tokio::test]
    async fn mark_served_clears_the_pending_slot() {
        let s = AskBackStore::open_in_memory().await.unwrap();
        let RecordOutcome::Inserted(id) = s.record(&mk("p", "ep-1", "Q1")).await.unwrap() else {
            panic!("expected Inserted");
        };
        s.mark_served(id).await.unwrap();
        assert!(!s.has_pending_for_project("p").await.unwrap());
        // Now a second ask-back for the same project can land.
        let outcome = s.record(&mk("p", "ep-2", "Q2")).await.unwrap();
        assert!(matches!(outcome, RecordOutcome::Inserted(_)));
        let pending = s.get_pending_for_project("p").await.unwrap().unwrap();
        assert_eq!(pending.question, "Q2");
    }

    #[tokio::test]
    async fn dismissed_also_clears_the_pending_slot() {
        let s = AskBackStore::open_in_memory().await.unwrap();
        let RecordOutcome::Inserted(id) = s.record(&mk("p", "ep-1", "Q1")).await.unwrap() else {
            panic!("expected Inserted");
        };
        s.mark_dismissed(id).await.unwrap();
        // Dismiss should free the project slot just like served.
        let outcome = s.record(&mk("p", "ep-2", "Q2")).await.unwrap();
        assert!(matches!(outcome, RecordOutcome::Inserted(_)));
    }

    #[tokio::test]
    async fn pending_slot_is_scoped_per_project() {
        let s = AskBackStore::open_in_memory().await.unwrap();
        assert!(matches!(
            s.record(&mk("a", "ep-1", "Q1")).await.unwrap(),
            RecordOutcome::Inserted(_)
        ));
        // Different project — should land independently.
        assert!(matches!(
            s.record(&mk("b", "ep-2", "Q2")).await.unwrap(),
            RecordOutcome::Inserted(_)
        ));
        assert!(s.has_pending_for_project("a").await.unwrap());
        assert!(s.has_pending_for_project("b").await.unwrap());
    }

    #[tokio::test]
    async fn get_pending_returns_none_when_only_served_exists() {
        let s = AskBackStore::open_in_memory().await.unwrap();
        let RecordOutcome::Inserted(id) = s.record(&mk("p", "ep-1", "Q1")).await.unwrap() else {
            panic!();
        };
        s.mark_served(id).await.unwrap();
        let pending = s.get_pending_for_project("p").await.unwrap();
        assert!(pending.is_none());
    }
}
